"""
Generate formatted HTML case-level explanations for clinician focus group review.

Each case shows patient demographics (anonymized), model prediction + confidence,
top features driving prediction with SHAP waterfall visualization, and blank
fields for clinician response.
"""

import json
from pathlib import Path

from audit.config import (
    EXPLAINABILITY_OUTPUT_DIR, TASK_DISPLAY_NAME,
    MODEL_DISPLAY_NAME, ensure_output_dirs,
)


_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Clinician Review: Model Explanation Cases</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; max-width: 900px; margin: 40px auto; color: #222; }}
  h1 {{ color: #1a5276; border-bottom: 3px solid #1a5276; padding-bottom: 10px; }}
  h2 {{ color: #2c3e50; margin-top: 40px; }}
  .case {{ border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin: 20px 0; background: #fafafa; page-break-inside: avoid; }}
  .case-header {{ background: #1a5276; color: white; padding: 10px 15px; border-radius: 6px 6px 0 0; margin: -20px -20px 15px -20px; }}
  .demographics {{ background: #eaf2f8; padding: 10px 15px; border-radius: 4px; margin: 10px 0; }}
  .prediction {{ font-size: 1.2em; padding: 10px 0; }}
  .prediction .prob {{ font-weight: bold; font-size: 1.3em; }}
  .correct {{ color: #27ae60; }}
  .incorrect {{ color: #c0392b; }}
  table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
  th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #ddd; }}
  th {{ background: #eaf2f8; font-weight: 600; }}
  .shap-bar {{ height: 18px; display: inline-block; border-radius: 3px; min-width: 2px; }}
  .shap-pos {{ background: #e74c3c; }}
  .shap-neg {{ background: #3498db; }}
  .review-section {{ background: #fef9e7; border: 1px solid #f9e79f; border-radius: 4px; padding: 15px; margin: 15px 0; }}
  .review-section label {{ font-weight: 600; display: block; margin: 10px 0 5px 0; }}
  .review-section input[type="text"], .review-section textarea {{ width: 95%; padding: 8px; border: 1px solid #ccc; border-radius: 4px; }}
  textarea {{ height: 60px; }}
  @media print {{ .case {{ page-break-inside: avoid; }} }}
</style>
</head>
<body>
<h1>Clinician Review: Model Prediction Explanations</h1>
<p>This document contains individual patient case explanations generated by machine learning models.
Each case shows the model's prediction, the features that most influenced the prediction, and
space for clinician feedback.</p>
<p><strong>Instructions:</strong> For each case, review the model's prediction and the features
that drove it. Then answer the review questions below each case.</p>
{cases_html}
</body>
</html>"""

_CASE_TEMPLATE = """
<div class="case">
  <div class="case-header">
    <strong>Case #{case_num}</strong> &mdash; {task_name} | {model_name}
  </div>

  <div class="demographics">
    <strong>Patient Demographics:</strong><br>
    {demographics_html}
  </div>

  <div class="prediction">
    Model Prediction: <span class="prob">{prediction:.1%}</span> probability of {outcome_name}<br>
    Actual Outcome: <strong class="{correct_class}">{actual_label}</strong>
  </div>

  <h3>Top Features Driving This Prediction</h3>
  <table>
    <tr><th>Feature</th><th>Patient Value</th><th>SHAP Contribution</th><th>Direction</th></tr>
    {features_html}
  </table>

  <div class="review-section">
    <h3>Clinician Review</h3>
    <label>1. Is this explanation clinically sufficient? (Y/N)</label>
    <input type="text" placeholder="Y / N">
    <label>2. What information is missing from this explanation?</label>
    <textarea placeholder="Enter any missing clinical context..."></textarea>
    <label>3. Would you override this model's recommendation? (Y/N) Why?</label>
    <textarea placeholder="Y/N and reasoning..."></textarea>
    <label>4. Rate the explanation quality (1-5, where 5 = excellent):</label>
    <input type="text" placeholder="1-5">
  </div>
</div>
"""


def generate_clinician_review_html(max_cases_per_model=20):
    """Generate an HTML report of patient-level explanations for clinician review.

    Args:
        max_cases_per_model: Maximum number of cases to include per model×task combo.

    Returns:
        Path to the generated HTML file.
    """
    ensure_output_dirs()

    expl_path = EXPLAINABILITY_OUTPUT_DIR / "individual_explanations.json"
    if not expl_path.exists():
        print("  Individual explanations not found, skipping clinician review")
        return None

    with open(expl_path) as f:
        explanations = json.load(f)

    # Limit cases per model×task
    seen_counts = {}
    filtered = []
    for ex in explanations:
        key = (ex["task"], ex["model"])
        seen_counts[key] = seen_counts.get(key, 0) + 1
        if seen_counts[key] <= max_cases_per_model:
            filtered.append(ex)

    cases_html_parts = []
    for i, ex in enumerate(filtered, 1):
        task = ex["task"]
        model = ex["model"]
        task_name = TASK_DISPLAY_NAME.get(task, task)
        model_name = MODEL_DISPLAY_NAME.get(model, model)

        # Demographics
        demo_parts = []
        demo_labels = {
            "ethnicity": "Race/Ethnicity",
            "gender": "Sex",
            "age": "Age",
            "anchor_age": "Age",
            "insurance": "Insurance",
        }
        for key, label in demo_labels.items():
            if key in ex["demographics"]:
                demo_parts.append(f"{label}: {ex['demographics'][key]}")
        demographics_html = " &bull; ".join(demo_parts)

        # Prediction info
        prediction = ex["prediction"]
        actual = ex["true_label"]
        predicted_positive = prediction >= 0.5
        correct = (predicted_positive and actual == 1) or (not predicted_positive and actual == 0)
        correct_class = "correct" if correct else "incorrect"
        actual_label = "Positive" if actual == 1 else "Negative"

        outcome_names = {
            "hospitalization": "hospitalization",
            "critical": "critical outcome (ICU/mortality)",
            "ed_reattendance": "72-hour ED return",
        }
        outcome_name = outcome_names.get(task, task)

        # Feature table
        features_rows = []
        max_shap = max(abs(f["shap_value"]) for f in ex["top_5_features"]) if ex["top_5_features"] else 1
        for feat in ex["top_5_features"]:
            bar_width = int(min(abs(feat["shap_value"]) / max_shap * 150, 150))
            bar_class = "shap-pos" if feat["shap_value"] > 0 else "shap-neg"
            direction = "Increases risk" if feat["shap_value"] > 0 else "Decreases risk"
            features_rows.append(
                f"<tr><td>{feat['feature']}</td>"
                f"<td>{feat['value']:.2f}</td>"
                f'<td><span class="shap-bar {bar_class}" style="width:{bar_width}px"></span> '
                f"{feat['shap_value']:.4f}</td>"
                f"<td>{direction}</td></tr>"
            )
        features_html = "\n    ".join(features_rows)

        cases_html_parts.append(_CASE_TEMPLATE.format(
            case_num=i,
            task_name=task_name,
            model_name=model_name,
            demographics_html=demographics_html,
            prediction=prediction,
            outcome_name=outcome_name,
            correct_class=correct_class,
            actual_label=actual_label,
            features_html=features_html,
        ))

    full_html = _HTML_TEMPLATE.format(cases_html="\n".join(cases_html_parts))

    out_path = EXPLAINABILITY_OUTPUT_DIR / "clinician_review.html"
    with open(out_path, "w") as f:
        f.write(full_html)
    print(f"  Clinician review document saved to {out_path}")
    return out_path


if __name__ == "__main__":
    generate_clinician_review_html()
